language: node_js

node_js:
  - '6'
  - '7'
  - '8'

install:
  - npm install -g codecov

script:
  - npm run pretest
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

cache:
  directories:
    - $HOME/.npm
