# serverless.yml
service: resize

plugins:
  - serverless-webpack
  - serverless-offline

custom: ${file(env.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${self:custom.dev.STAGE}
  timeout: 5 # optional, in seconds, default is 6
  environment:
    BUCKET: ${self:custom.dev.BUCKET}
    URL: ${self:custom.dev.URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

# you can add packaging information here
package:
  exclude:
    - ./**

functions:
  handler:
    handler: src/handler.imageprocess
    name: resizes3image
    memorySize: ${self:custom.dev.MEMORY_SIZE}
    timeout: ${self:custom.dev.TIMEOUT}
    reservedConcurrency: ${self:custom.dev.TIMEOUT}
    events:
      - http:
          path: /{key+}
          method: get
          integration: lambda-proxy
          parameters:
            paths:
              key: true
    environment:
      BUCKET: ${self:custom.dev.BUCKET}
      URL: ${self:custom.dev.URL}
