# serverless.yml
service: resizeS3image

plugins:
  - serverless-webpack
  - serverless-offline

custom: ${file(env.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage,'dev'}
  timeout: 5 # optional, in seconds, default is 6
  environment:
    BUCKET: ${self:custom.${self:provider.stage}.BUCKET}
    URL: ${self:custom.${self:provider.stage}.URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:PutObjectAcl'
        - 's3:PutObject'
        - 's3:ListBucket'
      Resource: '*'

# you can add packaging information here
package:
  exclude:
    - ./**

functions:
  handler:
    handler: src/handler.imageprocess
    name: resizeimage-${self:provider.stage}
    memorySize: ${self:custom.${self:provider.stage}.MEMORY_SIZE}
    timeout: ${self:custom.${self:provider.stage}.TIMEOUT}
    reservedConcurrency: ${self:custom.${self:provider.stage}.TIMEOUT}
    events:
      - http:
          path: /{key+}
          method: get
          integration: lambda-proxy
          cors:
            origins:
              - ${self:custom.${self:provider.stage}.ORIGIN}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: true
          parameters:
            paths:
              key: true
    environment:
      BUCKET: ${self:custom.${self:provider.stage}.BUCKET}
      URL: ${self:custom.${self:provider.stage}.URL}
